name: try deploy on docker

on:
  push:
    branches:
      - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout node
              uses: actions/checkout@v2
            - name: login docker
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: build and push docker image
              id: push
              uses: docker/build-push-action@v2
              with:
                context: .
                file: Dockerfile
                push: true
                tags: latest
                labels: latest
            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v2
              with:
                subject-name: index.docker.io/baghdasaryanparis/backend
                subject-digest: ${{ steps.push.outputs.digest }}